export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SHOW_COLORS = "SHOW_COLORS";
export const LOADING_TRANSACTIONS = "LOADING";
export const ERROR_TRANSACTIONS = "ERROR TRANSACTIONS";
export const SHOW_NOTIFICATIONS = "SHOW_NOTIFICATIONS";
